### ISSUE TITLE
Linux x64 support meta issue

### ISSUE THREAD

**Issue by PathogenDavid** [InfectedLibraries/Biohazrd#108]
* [ ] Need to handle the ordering different of `retbuf` and `this`
* [ ] `CSharpBuiltinTypeTransformation` needs to support the different sizes Linux uses for some types:
  * [ ] `long` is 64 bits
  * [ ] `wchar_t` is 32 bits

**Comment by PathogenDavid** [comment]
Details on adding support for the ELF tests on Windows:

I ran some tests on Alloy (See the `MakeSharedLibraryElfWindows` playground) and we can use the Visual Studio-provided Clang to build a Linux ELF shared library with some tweaks to our command:

* Add `-fuse-ld=lld` to make it use lld instead of trying (and failing) to use ld
* Add `--no-standard-libraries` to avoid having it trying to link to glibc and such (we don't need them for these tiny test libraries

Since the `--no-standard-libraries` thing is very atypical, we should not add that unconditionally on Linux.

---------

Additionally we need to use the Visual Studio setup API to locate the an install which has the LLVM toolset component installed.

--------

The skeleton of the logic is already there, but I think we should implement things such that the tests are skipped on Windows if Clang is not installed except if we're running on CI. (That way we don't have to make people install a huge toolset they won't usually be using.)

---------

One thing that is less clear is how to handle skipping these tests if we end up merging the two `LinkImportsTransformation` tests into one. XUnit doesn't support dynamic skipping until the new release is finished.
