### ISSUE TITLE
December Roadmap

### ISSUE THREAD

**Issue by PathogenDavid** [InfectedLibraries/Biohazrd#121]
Posting this a little later than I should've. Here's what I plan to focus on for December:

* [ ] Improve the usability of constructors and destructors. (Calling constructors is unnecessarily unnatural, some can’t be called at all.) https://github.com/InfectedLibraries/Biohazrd/issues/12 https://github.com/InfectedLibraries/Biohazrd/issues/31
  * (This was originally planned for November and ended up slipping.)
* [ ] Continue working on documentation. (In particular: Documentation for extending Biohazrd.)
* [ ] Continue adding automated testing to Biohazrd.
* [x] Prioritize the ~100 issues I've accumulated. (Some are really low priority and more a note to self and some are ticking time bombs that need to be resolved before they cause someone issues.) Done: https://github.com/InfectedLibraries/Biohazrd/projects/1
* [ ] Explore revamping the diagnostics system. (I'm pretty unhappy with it right now, it's too free-form.)
* [ ] Explore making a transformation pipeline debugger tool.
* [ ] Implement auto-generation of string marshaling in [InfectedImGui](https://github.com/InfectedLibraries/InfectedImGui).
* [ ] Test Biohazrd with OpenCV.
