### ISSUE TITLE
Inheriting from C++ classes from C# meta issue

### ISSUE THREAD

**Issue by PathogenDavid** [InfectedLibraries/Biohazrd#163]
* [ ] Exporting of protected inline https://github.com/InfectedLibraries/Biohazrd/issues/162
* [ ] Making it easier to use protected methods correctly https://github.com/InfectedLibraries/Biohazrd/issues/105
* [ ] Calling abstract constructors https://github.com/InfectedLibraries/Biohazrd/issues/14

The more I think about this, the more I think the only way to do this sanely will be to provide friendly C# classes to inherit from. InfectedTensorRT has [`ManagedLoggerBase`](https://github.com/InfectedLibraries/InfectedTensorRT/blob/a199e9580e343aec5d5c0e6873be93292a8413dd/InfectedTensorRT/ManagedLoggerBase.cs) as a proof of concept of what these classes might look like.
