### ISSUE TITLE
Function ABI handling rework meta issue

### ISSUE THREAD

**Issue by PathogenDavid** [InfectedLibraries/Biohazrd#198]
The following issues should all be closed by [`function-arrangement-rework`](https://github.com/InfectedLibraries/Biohazrd/tree/function-arrangement-rework) when it is merged into main:

* [x] https://github.com/InfectedLibraries/Biohazrd/issues/35
* [x] https://github.com/InfectedLibraries/Biohazrd/issues/53
* [x] https://github.com/InfectedLibraries/Biohazrd/issues/103
* [x] https://github.com/InfectedLibraries/Biohazrd/issues/134
* [x] https://github.com/InfectedLibraries/Biohazrd/issues/135
* [x] https://github.com/InfectedLibraries/Biohazrd/issues/147
* [x] https://github.com/InfectedLibraries/Biohazrd/issues/150
* [x] https://github.com/InfectedLibraries/Biohazrd/issues/186
* [x] https://github.com/InfectedLibraries/Biohazrd/issues/187

This effort also contributes a lot to https://github.com/InfectedLibraries/Biohazrd/issues/108

Remaining work before merge to main:

* [x] Write tests for ABI handling of function pointers
* [x] Test with OpenCV
* [x] Fix booleans (and maybe char?) in vtables
* [x] Figure out how to work around STL requiring Clang 11 for CI purposes (and maybe for non-CI purposes too since it's annoying to work around. it.) - https://github.com/InfectedLibraries/Biohazrd/issues/176
* [x] Remove obsoleted stuff. (The changes for this ended up breaking some API stuff so might as well rip off the bandaid.)
