### ISSUE TITLE
Meta: Improve friendliness of building vtables

### ISSUE THREAD

**Issue by PathogenDavid** [InfectedLibraries/Biohazrd#89]
Building vtables to create C# classes derived from C++ ones is rather tedious and error-prone in Biohazrd. This issue tracks ideas for ways we could improve this situation.

* [ ] Create an anlyzer to error when pure virtual methods aren't overridden.
* [ ] Make helpers for building vtables.
* [ ] Create guidance on extending vtables in C# to include a GCHandle.
* [ ] Provide a way to get the base vtable of a C++ type.
  * Is there an easy way to do this without initializing the base class?
  * Since C++'s vtable initialization semantics are completely different from C#'s*, we could get away with creating the modified vtable lazily and end up with the right result. Need to do a little research of how C++ handles this. (Does the derived vtable get fully populated at compile time or only the differences? -- Seems to be fully populated based on [this test](https://godbolt.org/z/hf8jsK). How does this work when `BaseClass` is in a DLL?)
  * *In C++, the vtable is initialized by the constructor (if it exists), so the base class doesn't have access to virtual methods in the derived class during construction. This is in contrast to the CLR, which initializes the vtable before any constructors are run. (For example, compare [this C++ example](https://godbolt.org/z/4js8va) with [this C# one](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMAjALABQZAQtHAMIA20UABMEwLxOZwDuAFAJQBuMsAB0AFTiwBw0rkIBOXgCI2a9Rs1btOtcqFkAIogCWANzgATeoyaX2nHjLKWJUmM/JyAzEwJMqKFoGKCgyAG8yJmi/X0DgxgEomMjSGPS/RRV4m1CQEABjGAB7BH1ZDJjJaQM0mIBfZOim2KYzEwQYdAg6PwAWJmqPfhb0tgA+TKVlHJCofKHyskavXF9/YwRzK1zmEADqXYiWtaZN7es5pLrK/eBqa/TUyuj5afOLS8Z8otKlm4yQ086RWLyYJ18xQsCC2ljg/UG7keLwmUxUHx2cwW7n+KyAA).)

**Comment by PathogenDavid** [comment]
Related: https://github.com/InfectedLibraries/Biohazrd/issues/192
