### ISSUE TITLE
November Roadmap

### ISSUE THREAD

**Issue by PathogenDavid** [InfectedLibraries/Biohazrd#95]
* [ ] Improve the usability of constructors and destructors. (Calling constructors is unnecessarily unnatural, some can’t be called at all.) https://github.com/InfectedLibraries/Biohazrd/issues/12 https://github.com/InfectedLibraries/Biohazrd/issues/31 https://github.com/InfectedLibraries/Biohazrd/issues/78
* [x] Begin proper documentation and improving the usability for third-party consumers.
* [x] Continue using the framework and output libraries (InfectedImGui and InfectedPhysX) to identify areas that could use improvement.
  * [ ] In particular, I want to port more of the PhysX samples to C#.
  * [x] A generator for TensorRT is contributing in this department as well: https://github.com/InfectedLibraries/Biohazrd/issues/83
* [x] Begin exploration of the “auto-generated safe interop” layer story.
  * Right now this is only possible in theory, little has been done in practice.
  * The beginning of this will probably be automatic generation of string marshaling in InfectedImGui. 
  * (https://github.com/InfectedLibraries/Biohazrd/issues/83 has been a bit of a testing ground for ideas in this department as well.)

**Comment by PathogenDavid** [comment]
(I plan to post the December roadmap and more detailed progress results for November eventually. Public bookkeeping in this regard got away from me.)
